### ISSUE TITLE
Add Jez Swanson on Fourier Transforms

### ISSUE THREAD

**Issue by simonw** [explorableexplanations/explorableexplanations.github.io#16]
http://www.jezzamon.com/fourier/index.html

**Comment by bryanbraun** [comment]
I'm not sure when, but it looks like this was added:

<img width="898" alt="Screen Shot 2022-07-10 at 5 53 37 PM" src="https://user-images.githubusercontent.com/1256329/178163410-fd062f6a-8d2b-4ebe-929f-3bf6ada2a265.png">

([see here for the code](https://github.com/explorableexplanations/explorableexplanations.github.io/blob/a819186abdb4a3c9d8c255d0f7e1d9e0f101095c/-data/explorables.csv#L151))

I think this can be closed now. 👍

**Comment by simonw** [comment]
Looks like it was added here: https://github.com/explorableexplanations/explorableexplanations.github.io/commit/cab6026bacb1c52b2cb700d1e5dcfa09050b6c02
